### PR TITLE
Adding initial ontology with core classes

### LINKED ISSUE #2: OWL ontology stub

### PR DESCRIPTION
**Pull request by escowles**
Fixes #2

### CODE REVIEW

**Comment by escowles** [comment]
Following the [Guidelines document](https://docs.google.com/document/d/1GCg6wDpQ-kVBnVQMPQxvlB-RDn6Qf5GJK_x2TwAIpK4/edit#heading=h.ysl93k4gtai7) but making a few changes:

* Explicitly declaring all of our PREMIS classes as subclasses of PROV classes.
* Only creating a single new predicate (`premis:governs`), and deferring the other new predicates to the preservation vocabularies instead.
* I also want to note that the preservation vocabularies contain terms that work in both directions, but creating subproperties of PROV properties will require creating separate terms for each direction.  So substantial revision will be required.

premis-relationships

**Comment by BertrandCaron** [comment]
Hi Esmé,

I think your proposal of reusing PROV properties everywhere it can be 
possible is convincing, thank you for that great input! I'm not sure about 
what you mean by "deferrin the other new predicates to the preservation 
vocabularies instead". I'd say that if PROV properties are top-level 
properties, vocabularies at id.loc.gov should be declared subproperties of 
their corresponding PROV superproperty, right?

About the relationship between Rights and Agent, I was completely wrong (I 
know little about PREMIS Rights, as it is the only PREMIS Entity we don't 
use at the BnF): the properties should be inverse, and prov:influenced / 
prov:wasInfluencedBy is indeed adapted.

After having discussed with Angela Dappert about Environments, I realized 
that the question is a little bit more complicated than what I thought at 
first. In fact, if you look at the vocabulary at 
http://id.loc.gov/vocabulary/preservation/linkingEnvironmentRole , you can 
see that this relationship is not specifically intended to point to a 
premis:Environment in a restrictive sense (an "IE of type Environment") 
but to any kind of PREMIS Object. If it points to a 
Representation/File/Bitstream, it means that the software/hardware Agent 
is also preserved in a repository as an Object; if it points to an IE, it 
means that the software/hardware Agent is also described generally as an 
IE in a repository or an Environment registry.
So I am not sure SKOS vocabularies are really adapted, as they would link 
possibly an Agent (an instance of software or hardware used to perform 
some preservation action) and the software or hardware model described in 
general or the Representation of such software or hardware stored in a 
repo, as source code or disk image.

That's a complex matter that we can discuss tomorrow...

All the best,


Bertrand Caron
Département des Métadonnées
Bibliothèque nationale de France
Quai François Mauriac
75706 Paris Cedex 13
01 53 79 42 23
bertrand.caron@bnf.fr




De :    Esmé Cowles <notifications@github.com>
A :     PREMIS-OWL-Revision-Team/revise-premis-owl 
<revise-premis-owl@noreply.github.com>
Cc :    Subscribed <subscribed@noreply.github.com>
Date :  04/04/2017 16:49
Objet : Re: [PREMIS-OWL-Revision-Team/revise-premis-owl] Adding initial 
ontology with core classes (#14)



Following the Guidelines document but making a few changes:
Explicitly declaring all of our PREMIS classes as subclasses of PROV 
classes.
Only creating a single new predicate (premis:governs), and deferring the 
other new predicates to the preservation vocabularies instead.
I also want to note that the preservation vocabularies contain terms that 
work in both directions, but creating subproperties of PROV properties 
will require creating separate terms for each direction. So substantial 
revision will be required.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Pass BnF lecture/culture illimité à 15 € / an  - Tout lire, tout voir, tout écouter ! –  Acheter en ligne Avant d'imprimer, pensez à l'environnement.

**Comment by escowles** [comment]
@BertrandCaron Based on our discussion yesterday, I have updated this pull request and my diagram:

premis-relationships

It seems like skos:exactMatch may be a good fit when linking to an IntellectualEntity, and relsubtype:isr (isRepresentedBy) is good when linking to a File/Bitstream representation.

**Comment by escowles** [comment]
@no-reply @azaroth42, I'd be particularly interested in your opinion of https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/pull/14/commits/80721ec1337f5119d4b36d50d76173188373c51e

PROV-O has a section on the inverse properties that are listed in a table, but not defined in the OWL ontology: https://www.w3.org/TR/prov-o/#inverse-names, which says "Modelers wishing to use inverses of the properties defined by PROV-O should use those reserved by this document."

**Comment by azaroth42** [comment]
Seems like a bug in the ontology?

**Comment by escowles** [comment]
@azaroth42 They say that all of the properties have inverse properties in theory, but they only define a handful to avoid placing the burden of supporting relationships in both directions for all users.  So there note says to use the "reserved" property names if you really want them, but gives no guidance on how to do that.

**Comment by azaroth42** [comment]
Rob-- you mention that we need to be careful about using PROV because of the messy rules. What are the rules that are messy and what should we avoid? We had thought we would use PROV where it seemed like it fit, but do you suggest rethinking that?

That seems like a bug in the WG / specification then! ;) 

I would be careful using prov though ... there are a lot of rules that can come back and make things very messy.  The Annotation work started using it, tried to solve the problems the rules created, found that the cost was far far greater than any value.

**Comment by BertrandCaron** [comment]
Hi Esmé,

Thank you very much for that, I have some remarks:
- I was surprised by the use of skos:exactMatch to bind together two 
resources that are instances of two different classes. But, as we consider 
Object and Agent are not necessarily disjoint, that could work.
- isRepresentedBy: that's the right property, but shouldn't we redefine it 
in the PREMIS ontology, because the relationship subtype vocabulary is 
meant to be used between Objects only? Hopefully that would bring some 
clarity to this difficult question...
- the arrow should point to Object, not specifically to Environment, as 
Environment is a subclass of IE in the ontology, whereas in the DD a 
linkingEnvironment semantic unit can point to any kind of Object.
- there is a missing "d" in "prov:wasAssociateFor".

I think that we should propose the solution skos:exactMatch / 
prremis/relSubType:isr to two of our colleagues who worked a lot on PREMIS 
3 and are not in the revision team (Angela Dappert and Sébastien Peyrard) 
and see what they think about it. I can do that in the next few days (A. 
Dappert said she needs some time to think about this!).

All the best,


Bertrand Caron
Département des Métadonnées
Bibliothèque nationale de France
Quai François Mauriac
75706 Paris Cedex 13
01 53 79 42 23
bertrand.caron@bnf.fr




De :    Esmé Cowles <notifications@github.com>
A :     PREMIS-OWL-Revision-Team/revise-premis-owl 
<revise-premis-owl@noreply.github.com>
Cc :    BertrandCaron <bertrand.caron@bnf.fr>, Mention 
<mention@noreply.github.com>
Date :  07/04/2017 21:44
Objet : Re: [PREMIS-OWL-Revision-Team/revise-premis-owl] Adding initial 
ontology with core classes (#14)



@BertrandCaron Based on our discussion yesterday, I have updated this pull 
request and my diagram:

It seems like skos:exactMatch may be a good fit when linking to an 
IntellectualEntity, and relsubtype:isr (isRepresentedBy) is good when 
linking to a File/Bitstream representation.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

Pass BnF lecture/culture illimité à 15 € / an  - Tout lire, tout voir, tout écouter ! –  Acheter en ligne Avant d'imprimer, pensez à l'environnement.

**Comment by angeladiiorio** [comment]
Dear Esme', 
I had a glance at the code,
actually a declaration in the ontology shouldn't refer out of our ontology competence...
this means that I can make declaration only for my ontological entities not for third party ontology.
This means that I can declare an ObjectProperty premis:[httpd prefix]wasUsedBy 
which is the inverseOf "http://www.w3.org/ns/prov#used", but is not straightforward...
I think also that for making use of the PROV-O entities is necessary to import the ontology, then we can express the following axioms.
 <owl:ObjectProperty rdf:about="http://id.loc.gov/premis/owl/v3/used">
        <owl:equivalentProperty rdf:resource="http://www.w3.org/ns/prov#used"/>
        <owl:inverseOf rdf:resource="http://id.loc.gov/premis/owl/v3/wasUsedBy"/>
    </owl:ObjectProperty>

**<owl:ObjectProperty rdf:about="http://id.loc.gov/premis/owl/v3/wasUsedBy">**
 +    <rdfs:label>was used by</rdfs:label>
 +    <owl:inverseOf rdf:resource="http://id.loc.gov/premis/owl/v3/used"/>
 +    <rdfs:domain rdf:resource="http://www.w3.org/ns/prov#Entity"/>
 +    <rdfs:range rdf:resource="http://www.w3.org/ns/prov#Activity"/>
 +    <rdfs:isDefinedBy rdf:resource="http://www.loc.gov/premis/rdf/v3/"/>
 +  </owl:ObjectProperty>

**Comment by escowles** [comment]
@BertrandCaron I would be interested in your colleagues' opinion of using skos:exactMatch and relsubtype:isr (isRepresentedBy).  I'm not sure we need to include isRepresentedBy in the main ontology or not — my thinking is that Agent and Object are not disjoint (as we discussed), so it's perfectly valid to consider an Agent an Object where it makes sense, and use the properties that are intended for linking Objects.  There may be other terms in the RelationshipSubType vocabulary that could be appropriate in certain circumstances.

For `wasAssociatedFor`, I am taking the term from the PROV OWL file:

```
:wasAssociatedWith
    a owl:ObjectProperty ;
    rdfs:comment "An prov:Agent that had some (unspecified) responsibility for the occurrence of this prov:Activity."@en ;
    rdfs:domain :Activity ;
    rdfs:isDefinedBy <http://www.w3.org/ns/prov-o#> ;
    rdfs:label "wasAssociatedWith" ;
    rdfs:range :Agent ;
    rdfs:subPropertyOf :wasInfluencedBy ;
    owl:propertyChainAxiom (:qualifiedAssociation
        :agent
    ) ;
    :category "starting-point" ;
    :component "agents-responsibility" ;
    :inverse "wasAssociateFor" ;
    :qualifiedForm :Association, :qualifiedAssociation .
```

Also, here is an updated diagram with the arrow from Agent pointing at Object, not Environment specifically:

premis-relationships

**Comment by escowles** [comment]
@angeladiiorio I agree that it is unusual and generally discouraged to define terms outside of an ontology's namespace.  But I am not sure how else to make sense of the comment in the PROV-O guidelines ([https://www.w3.org/TR/prov-o/#inverse-names](https://www.w3.org/TR/prov-o/#inverse-names)), which says "Modelers wishing to use inverses of the properties defined by PROV-O should use those reserved by this document."

Perhaps we should create a separate ontology file which only defines these two predicates that are suggested by PROV-O as inverse properties?

**Comment by BertrandCaron** [comment]
@escowles I asked Sébastien Peyrard about this question.
- about skos:exactMatch, he agrees on the use of this property. He even considers that we could use skos:closeMatch / skos:exactMatch for linking Environments and Formats to their equivalent in external registries (we chose rdfs:seeAlso).
- About relsubtype:isr, he also agrees and considers both options (reusing the property defined as a preservation vocabulary or redefining it in the ontology) to be equally acceptable.

I'll ask Angela Dappert the same question as soon as she has enough time to dive into it...

By the way, is everyone in the group notified when we discuss in Github? Shouldn't we continue discussing in the Google group in order to keep all information in the same place?

Best,

Bertrand

**Comment by rguenther52** [comment]
(I thought I just wrote this but it seems to have disappeared-- sorry if it's a repeat).
Rob-- what did you mean by needing to be careful about using PROV because of messy rules? What are those messy rules? We had thought we would use PROV heavily where it seemed to fit, but should we rethink that strategy? You mentioned the Annotations work and that attempt.

**Comment by escowles** [comment]
Moving discussion to Google Docs version: https://docs.google.com/document/d/1wNuzl5hkv5Ypoyd6Z2wgADGQy5pZchbzPyj-IFKhi5Y/edit

**Comment by escowles** [comment]
Closing in favor of #15

**Pull request closed without merging**
